require 'sqlite3'
require 'singleton'
require 'byebug'

require_relative 'questiondatabase'
require_relative 'question_follow'
require_relative 'question'
require_relative 'question_like'
require_relative 'reply'
require_relative 'user'
require_relative 'table'
